### ISSUE TITLE
Style compatibility with same key

### ISSUE THREAD

**Issue by cristovao-trevisan** [vuejs/babel-plugin-transform-vue-jsx#128]
Sometimes it's needed to set two styles for the same key, example:

```css
.flex-box {
  display: -webkit-flex; /* Safari */
  display: flex;
}
```

It would be nice to have a way to do this without css, example:

```js
const myStyle = {
  display: ['-webkit-flex',  'flex']
}
```
